version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo-server

  redis:
    image: redis:7
    container_name: redis-server

  node1:
    build: .
    container_name: node-server-1
    environment:
      - SERVER_NAME=node-server-1
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/redisDemo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_CACHE=true
    depends_on:
      - mongo
      - redis

  node2:
    build: .
    container_name: node-server-2
    environment:
      - SERVER_NAME=node-server-2
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/redisDemo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_CACHE=true
    depends_on:
      - mongo
      - redis

  node3:
    build: .
    container_name: node-server-3
    environment:
      - SERVER_NAME=node-server-3
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/redisDemo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - USE_CACHE=true
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3
